### ISSUE TITLE
Create AD group for application

### ISSUE THREAD

**Issue by mcritchlow** [ucsdlib/earp#17]
We need an AD group for admins in this application.

Then add to secrets and wire up for admin group AD query.

Something like `lib-earp-ro` or something? I'm not sure the right naming convention.

/cc @rstanonik @jhriv

**Comment by mcritchlow** [comment]
@rstanonik or @jhriv - Could I have an AD group setup for this application. I can give you the initial list of people via Slack whenever you're ready. Thanks

**Comment by rstanonik** [comment]
slack me the list

**Comment by mcritchlow** [comment]
Done and verified in the code, thanks @rstanonik!
